# Generated by Django 4.0.4 on 2022-05-30 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
