# Generated by Django 4.0.4 on 2022-05-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mpesa',
            field=models.CharField(default='QELYTTE7JHN', max_length=10),
            preserve_default=False,
        ),
    ]
