# Generated by Django 4.0.4 on 2022-05-27 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_order_mpesa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='order',
            name='zipcode',
        ),
    ]
