# Generated by Django 4.0.4 on 2022-05-27 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_rename_address_order_location_remove_order_zipcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='place',
        ),
    ]
